//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruFileUrl
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserName { get; set; }
        public string File { get; internal set; }
    }
}
